name: example
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  deact: ^1.0.0
  deact_router:
    path: ../

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lint: ^1.7.2
