name: example
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  deact: ^1.0.0
  deact_router:
    path: ../

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lint: ^1.7.2
  webdev: ^2.7.7
